import { ProjectData } from "../types/ProjectData";

const boxedUp: ProjectData = {
    title: "Boxed Up",
    year: 2024,
    type: "Personal, Solo",
    tools: ["Typescript", "HTML/CSS", "Electron", "Socketio", "Express", "Node.js"],
    accomplishments: ["Created locally hosted multiplayer game using socket.io and express", "Taught myself electron to create a desktop app", "Used HTML/CSS for the frontend", "Published game to gamejolt.com", "Used Github for version control"],
    about: "BoxedUp is a collection of locally run party-style games that players can join and play together. Players can join the game by connecting to the host server via local ip, or scanning a qr code generated by the host app. The game keeps track of scores and displays them on a leaderboard at the end of each round. This project was a great learning experience in full-stack development and real-time web applications.",
    images: null,
    youtubeLink: null
}

export default boxedUp;